#1
cliente=input("ingrese el nombre del cliente:")
kg=int(input("ingrese nro de kg de manzanas:"))
precio=float(input("ingrese precio de cada unidad:"))
total=(precio*kg)
comprador_compulsivo = (total > 130)
print(" + #################### +")
print(" + # voleta de compra  +")
print(" + #################### +")
print("#")
print(" + # cliente:",cliente)
print(" + # item :",kg," kg manzanas")
print(" + # P.U. : s/.",precio)
print(" + # total : s/",total)
print(" + #################### +")
print("comprador_compulsivo?:",comprador_compulsivo)