#10
cliente=input("ingrese el nombre del cliente:")
oc=int(input("ingrese los platos pedidos de comida:"))
precio=float(input("ingrese precio de cada pedido:"))
total=(precio*oc)
comprador_compulsivo = (total > 130)
print(" + #################### +")
print(" + # voleta de pago  +")
print(" + #################### +")
print("#")
print(" + # cliente:",cliente)
print(" + # item :",oc,"platos de comida")
print(" + # P.U. : s/.",precio)
print(" + # total : s/",total)
print(" + #################### +")
print("comprador_compulsivo?:",comprador_compulsivo)