#11
cliente=input("ingrese el nombre del cliente:")
zapatos=int(input("ingrese la cantidad de pares de zapatos comprados:"))
pantalon=int(input("ingrese la cantidad de pantalones comprados:"))
polos=int(input("ingrese la cantidad de polos comprados:"))
precio1=float(input("ingrese el precio de par de zapatos:"))
precio2=float(input("ingrese el precio de un pantalon:"))
precio3=float(input("ingrese el precio de un polo:"))
gasto1=(zapatos*precio1)
gasto2=(zapatos*precio2)
gasto3=(zapatos*precio3)
gasto_total=(gasto1+gasto2+gasto3)
lugar_de_marca =( gasto1+gasto2+gasto3>500)
print(" + #################### +")
print(" + # voleta de compra  +")
print(" + # topitop  +")
print(" + #################### +")
print("#")
print(" + # cliente:",cliente)
print(" + # zapatos:",zapatos,"comprados")
print(" + # pantalon:",pantalon,"comprados")
print(" + # polos:",polos,"comprados")
print(" + # gasto1 : s/",gasto1)
print(" + # gasto2 : s/",gasto2)
print(" + # gasto3 : s/",gasto3)
print(" + # gasto_total : s/",gasto_total)
print(" + #################### +")
print("lugar_de_marca?:",lugar_de_marca)