#13
ferreteria=input("ingrese el nombre de la ferreteria:")
f=int(input("ingrese la cantidad de fierro comprado:"))
precio=float(input("ingrese precio de c.u de fierro:"))
total=(precio*f)
tienda_grande= (total > 600)
print(" + #################### +")
print(" + # voleta de compra  +")
print(" + #################### +")
print("#")
print(" + # ferreteria:",ferreteria)
print(" + # item :",f," fierros")
print(" + # P.U. : s/.",precio)
print(" + # total : s/",total)
print(" + #################### +")
print("tienda_grande?:",tienda_grande)
