#14
cantante=input("ingrese el nombre del cantante:")
conciertos=int(input("ingrese el numero de conciertos:"))
cobro=float(input("ingrese el cobro por concierto"))
ganancia=(cobro*conciertos)
artista_favorita=(ganancia>1000)
print("################")
print("# NOCHE DE CANCIONES #")
print("################")
print("#")
print("# conciertos:",conciertos)
print("# cobro:s/",cobro)
print("# ganancia:",ganancia)
print("################")
print("artista_favorita?",artista_favorita)
