#15
pintor=input("ingres el nombre del pintor:")
metro=int(input("ingrese los metros que pintara:"))
costo=float(input("ingrese el costo por metro"))
total=(metro*costo)
trabajador_profesional=(total>500)
print("###################")
print("# PAGO POR PINTAR #")
print("###################")
print("#")
print("# PINTOR:",pintor)
print("# METRO:",metro,"metros")
print("# costo:s/",costo)
print("# total:s/",total)
print("###################")
print("trabajador_profesional?",trabajador_profesional)
