#16
docente=input("ingrese el nombre del docente:")
h=int(input("ingrese nro de horas de clase:"))
d=int(input("ingrese los dias de clase:"))
precio=float(input("ingrese precio por hora de clase:"))
sueldo=(precio*h*d)
profesor_aplicado = (sueldo > 1200 )
print(" + #################### +")
print(" + # pago por horas de clases +")
print(" + #################### +")
print("#")
print(" + # docente:",docente)
print(" + # item:",h,"horas de clase")
print(" + # dias:",d)
print(" + # precio : s/.",precio)
print(" + # sueldo: s/",sueldo)
print(" + #################### +")
print("profesor_aplicado?:",profesor_aplicado)