#18
cateto_1=float(input("ingrese el valor del cateto 1:"))
cateto_2=float(input("ingrese el valor del cateto 2:"))
hipotenusa=((cateto_1**2)+(cateto_2**2))**(1/2)
c = (hipotenusa > 300)
print(" + #################### +")
print(" + # Boleta de Triangulo  +")
print(" + #################### +")
print("#")
print(" + # cateto 1:",cateto_1)
print(" + # cateto2 :",cateto_2)
print(" + # hipotenusa :",hipotenusa)
print(" + #################### +")
print("triangulo gigante?:",c)