#2
trabajador=input("ingrese el nombre del trabajador:")
dias=int(input("ingrese el numero de dias que trabaja:"))
precio=float(input("pago por trabajo diario:"))
cobro=(dias*precio)
trabajador_moderado = (cobro > 300)
print(" + #################### +")
print(" + # voleta de Pago  +")
print(" + #################### +")
print("#")
print(" + # trabajador:",trabajador)
print(" + # item :",dias," dias trabajados")
print(" + # precio por trabajar : s/.",precio)
print(" + # total en cobrar : s/",cobro)
print(" + #################### +")
print("trabajador_moderado?:",trabajador_moderado)