#5
cliente=input("ingrese el nombre del cliente:")
h=float(input("ingrese las horas :"))
ph=float(input("ingrese el precio por hora:"))
internet=(h*ph)
cliente_vicioso = (internet>4)
print(" + #################### +")
print(" + # boleta de redes sociales  +")
print(" + #################### +")
print("#")
print(" + # cliente:",cliente)
print(" + # item :",h," horas en internet")
print(" + # item ph: s/",ph)
print(" + # internet : s/",internet,"gasta")
print(" + #################### +")
print("cliente_vicioso?:",cliente_vicioso)