#6
mes=input("ingrese el nombre del mes:")
dias=int(input("ingrese el numero de dias de consumo:"))
precio=float(input("ingrese el precio de la pizza:"))
pago=(precio*dias)
el_mes_con_plata = (pago>100)
print(" + #################### +")
print(" + # boleta de consumo +")
print(" + #################### +")
print("#")
print(" + # mes:",mes)
print(" + # dias :",dias,"de consumo")
print(" + # P.U.: s/",precio)
print(" + # pago: s/",pago,"total a pagar")
print(" + #################### +")
print("el_mes_con_plata?:",el_mes_con_plata)