#7
apuesta=int(input("ingresa tu numero de la apuesta:"))
dias=int(input("ingrese el numero de dias que juegas:"))
precio=float(input("ingrese el precio del juego por dia:"))
pago=(dias*precio)
juego_extremo= (pago>150)
print(" + #################### +")
print(" + # boleta de juego  +")
print(" + #################### +")
print("#")
print(" + # apuesta:",apuesta)
print(" + # dias:",dias)
print(" + # item precio: s/",precio)
print(" + # pago: s/",pago)
print(" + #################### +")
print("juego_extremo?:",juego_extremo)