#9
doctor=input("ingrese el nombre del doctor:")
e=int(input("ingrese la cantidad de enfermos:"))
precio=float(input("ingrese precio por cada cita:"))
ganancia=(e*precio)
medico_de_primera = (ganancia > 1300)
print(" ####################")
print(" # voleta de cita ")
print(" ####################")
print("#")
print("# doctor:",doctor)
print(" + # atendio a :",e,"enfermos")
print(" + # P.cita. : s/.",precio)
print(" + # ganancia: s/",ganancia)
print(" + #################### +")
print("medico_de_primera?:",medico_de_primera)